package com.khorn.terraincontrol.generator.biome.layers;

import com.khorn.terraincontrol.generator.biome.ArraysCache;
import com.khorn.terraincontrol.util.minecraftTypes.DefaultBiome;

public class LayerRareBiome extends Layer
{

    public LayerRareBiome(long seed, Layer parentLayer)
    {
        super(seed);
        this.child = parentLayer;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be
     * interpreted as temperatures, rainfall amounts, or biomeList[] indices
     * based on the particular GenLayer subclass.
     */
    @Override
    public int[] getInts(ArraysCache cache, int x, int z, int xSize, int zSize)
    {
        int[] childInts = this.child.getInts(cache, x - 1, z - 1, xSize + 2, zSize + 2);
        int[] thisInts = cache.getArray(xSize * zSize);

        for (int zi = 0; zi < zSize; ++zi)
        {
            for (int xi = 0; xi < xSize; ++xi)
            {
                this.initChunkSeed((long) (xi + x), (long) (zi + z));
                int selection = childInts[xi + 1 + (zi + 1) * (xSize + 2)];

                if (this.nextInt(57) == 0)
                {
                    if (selection == DefaultBiome.PLAINS.Id)
                    {
                        thisInts[xi + zi * xSize] = DefaultBiome.PLAINS.Id + 128;
                    } else
                    {
                        thisInts[xi + zi * xSize] = selection;
                    }
                } else
                {
                    thisInts[xi + zi * xSize] = selection;
                }
            }
        }

        return thisInts;
    }

}
